image: infocorpjr/laravel

stages:
  - build
  - test
  - deploy

before_script:
  - export TERM=linux
  - export DEBIAN_FRONTEND=noninteractive

################################################################################
# BUILD STAGE                                                                  #
################################################################################

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-environment
    paths:
      - tests/Browser/screenshots/
      - vendor/
      - node_modules/
      - .env
  artifacts:
    expire_in: 2h
    paths:
      - tests/Browser/screenshots/
      - vendor/
      - node_modules/
      - .env
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - npm install
    - npm run prod
    - cp .env.example .env
    - php artisan key:generate
    - chown www-data:www-data storage -R


################################################################################
# TEST STAGE                                                                   #
################################################################################

codestyle:
  stage: test
  script:
    # Verificação do padrão PSR2.
    - vendor/bin/phpcs --standard=PSR2 --extensions=php app

# IMPORTANTE! Testa a migração do banco do banco de dados (NO SQLITE)
database:
  stage: test
  script:
    - touch database/database.sqlite
    - php artisan migrate --seed

phpunit:
  stage: test
  script:
    - touch database/database.sqlite
    - vendor/bin/phpunit --coverage-text --colors=never

# DESATIVADO!
.e2e:
  stage: test
  script:
    - rm -R /var/www
    - ln -s $CI_PROJECT_DIR /var/www
    - touch database/database.sqlite
    - php artisan migrate
    - /etc/init.d/apache2 start
    - php artisan dusk

################################################################################
# DEPLOY STAGE                                                                 #
################################################################################

.init_ssh: &init_ssh |
  eval $(ssh-agent   -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  ssh-keyscan "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  chmod 644 ~/.ssh/known_hosts
  ssh -T suporte@"$SSH_KNOWN_HOSTS"

## Faz a configuração do servidor apache

.apache2: &apache2 |
  sudo echo "
  <VirtualHost *:80>
  ServerAdmin suporte@infocorp.ic.ufmt.br
  ServerName review5.infocorpjr.com
  ServerAlias www.review5.infocorpjr.com
  DocumentRoot /var/www/review5.infocorpjr.com/public
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined
  <Directory /var/www/review5.infocorpjr.com/public>Allowoverride All</Directory>
  </VirtualHost>" | sudo tee /etc/apache2/sites-available/$DOMAIN.conf

deploy_review:
  stage: deploy
  script:
    - *init_ssh
    - *apache2
  environment:
    name: review
    url: http://review5.infocorpjr.com
  only:
    - master